repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
    exclude: test
    args: [--maxkb=500]

    # python import sorting - will amend files
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort

    # python code formatting - will amend files
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black

    # python static type checking
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910-1
  hooks:
  - id: mypy
    additional_dependencies: [types-all]

    # pylint
- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v3.0.0a4
  hooks:
  - id: pylint
    args: [--disable=import-error]

    # flake8
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args: [--max-line-length=119, "--extend-ignore=E203"]
